version: "3.9"

services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - devops-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

